name: Unittests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
          - operating-system: macos-latest
            python-version: '3.12'

          - operating-system: windows-latest
            python-version: '3.12'

          - operating-system: ubuntu-latest
            python-version: '3.12'

          - operating-system: ubuntu-latest
            python-version: '3.11'

          - operating-system: ubuntu-latest
            python-version: '3.10'

    steps:
    - uses: actions/checkout@v4
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        environment-file: environment.yml
        use-mamba: true
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 6
      run: |
        pip install . --no-deps --no-build-isolation
        python -m unittest discover tests
